### PR TITLE
Check If wm supports minimizing before creating it in linux

### PR DESCRIPTION
**Pull request by Clutchnp**
It should only render the minimize button if the x enviornment supports it.

### CODE REVIEW

**Comment by Clutchnp** [comment]
How does the title bar's width change based on  weather resize flag is set or not ? We should do the same thing with this, if the window  can minimize title bar should shrink to give it space else if it cannot, title bar  should take the space of the minimize button @bendikMichal

**Comment by bendikMichal** [comment]
Yeah, we should do sth like that. I'm thinking make a function that gets it since there would more options that change it...

**Comment by Clutchnp** [comment]
i dont think a new function is needed, only so many things can affect the title bar, but  I would recommend changing the way neg variable is handled

**Comment by bendikMichal** [comment]
Seems good. Thanks for contributing, much appreciated.

**Pull request merged**
